In [82]:
import json
import numpy as np
import pandas as pd
import ast

In [50]:
business_data = []
with open('business.json') as f:
    for line in f:
        business_data.append(json.loads(line))
business_df = pd.DataFrame.from_dict(business_data)
business_df.head()

target = pd.read_csv("restaurantfinal.csv")

In [51]:
target

,Unnamed: 0,X,business_id,city,postal_code,stars,review_count,Type,hours_per_week,weight
0,1,0,-3AooxIkg38UyUdlz5oXdw,Santa Barbara,93101,3.0,436,Italian,69.9,1.776346
1,2,7,-BdYhP-12elmFV7oB1iv4A,Santa Barbara,93109,5.0,41,American,45.0,0.167042
2,3,14,-nwNPb3G-0L95igrhkvMtw,Santa Barbara,93101,2.5,46,Fast Food,67.9,0.187413
3,4,21,-r6nmLB5Vi2TLQCxh0_dtw,Santa Barbara,93101,4.0,215,Deli,42.0,0.875950
4,5,28,04Ss49U_QKYLotcJMAH8cA,Santa Barbara,93101,4.0,97,Deli,56.0,0.395196
...,...,...,...,...,...,...,...,...,...,...
444,445,3108,z9-8KvMAlVK46De-G3sNJQ,Santa Barbara,93101,4.0,239,Healthy,84.0,0.973731
445,446,3115,zJpZ-uQ_F0XVgK1u98uWSg,Santa Barbara,93101,4.5,13,Mexican,28.2,0.052964
446,447,3122,zZrDoiQIUmiVkifJx0h_KA,Santa Barbara,93101,4.5,8,Coffee,77.0,0.032594
447,448,3129,zeAfmYy9b1gfUJLRBHm6vQ,Santa Barbara,93105,4.0,240,Italian,74.6,0.977805
448,449,3136,ziXR7sUrbKRCNeDqfjibUg,Santa Barbara,93101,4.0,262,Mexican,97.0,1.067437

In [52]:
business_df = business_df[business_df.business_id.isin(target["business_id"].values)]

In [54]:
business_df.reset_index(inplace=True)
business_df.drop("index",axis=1,inplace=True)

31     -3AooxIkg38UyUdlz5oXdw
404    -BdYhP-12elmFV7oB1iv4A
433    -nwNPb3G-0L95igrhkvMtw
136    -r6nmLB5Vi2TLQCxh0_dtw
384    04Ss49U_QKYLotcJMAH8cA
                ...
119    z9-8KvMAlVK46De-G3sNJQ
107    zJpZ-uQ_F0XVgK1u98uWSg
323    zZrDoiQIUmiVkifJx0h_KA
337    zeAfmYy9b1gfUJLRBHm6vQ
344    ziXR7sUrbKRCNeDqfjibUg
Name: business_id, Length: 449, dtype: object

In [60]:
business_df = business_df.sort_values(by=["business_id"])

In [72]:
newdf = pd.DataFrame(business_df['attributes'].to_dict()).T

In [106]:
newdf.BusinessParking.replace({np.nan: "None"}, inplace=True)

In [111]:
newdf.Ambience.replace({np.nan: "None"}, inplace=True)

In [114]:
newdf.BestNights.replace({np.nan: "None"}, inplace=True)

In [116]:
newdf.GoodForMeal.replace({np.nan: "None"}, inplace=True)

In [119]:
newdf.Music.replace({np.nan: "None"}, inplace=True)

In [108]:
newdf['BusinessParking'] = newdf['BusinessParking'].apply(ast.literal_eval)
newdf['Ambience'] = newdf['Ambience'].apply(ast.literal_eval)
newdf['BestNights'] = newdf['BestNights'].apply(ast.literal_eval)
newdf['GoodForMeal'] = newdf['GoodForMeal'].apply(ast.literal_eval)
newdf['Music'] = newdf['Music'].apply(ast.literal_eval)

In [127]:
newdf['Ambience'] = newdf['Ambience'].apply(ast.literal_eval)
newdf['BestNights'] = newdf['BestNights'].apply(ast.literal_eval)
newdf['GoodForMeal'] = newdf['GoodForMeal'].apply(ast.literal_eval)
newdf['Music'] = newdf['Music'].apply(ast.literal_eval)

In [129]:
newdf

,NoiseLevel,BusinessParking,RestaurantsReservations,Alcohol,RestaurantsPriceRange2,BusinessAcceptsCreditCards,OutdoorSeating,BikeParking,WiFi,RestaurantsTakeOut,...,Smoking,BusinessAcceptsBitcoin,DriveThru,ByAppointmentOnly,BYOBCorkage,Corkage,AgesAllowed,Open24Hours,DietaryRestrictions,RestaurantsCounterService
31,u'average',"{'garage': False, 'street': True, 'validated':...",True,'full_bar',2,True,True,True,u'free',True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
404,NaN,"{'garage': False, 'street': False, 'validated'...",False,u'beer_and_wine',NaN,True,True,True,NaN,True,...,u'no',False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
433,u'average',"{'garage': False, 'street': False, 'validated'...",False,u'none',1,True,True,True,'no',True,...,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,u'average',"{'garage': None, 'street': True, 'validated': ...",False,u'none',1,True,True,True,'free',True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
384,NaN,"{'garage': False, 'street': False, 'validated'...",False,u'none',2,True,None,NaN,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,u'loud',"{'garage': False, 'street': True, 'validated':...",False,'none',1,True,None,True,u'no',True,...,NaN,NaN,NaN,NaN,'yes_free',False,NaN,NaN,NaN,NaN
107,NaN,None,NaN,u'none',NaN,True,True,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,u'average',"{'valet': False, 'garage': None, 'street': Non...",NaN,NaN,NaN,NaN,True,NaN,u'free',NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,u'average',"{'garage': False, 'street': False, 'validated'...",False,u'beer_and_wine',2,True,None,True,u'no',None,...,NaN,NaN,True,False,NaN,NaN,NaN,NaN,NaN,NaN
344,u'average',"{'garage': False, 'street': False, 'validated'...",False,u'beer_and_wine',1,True,True,True,u'no',True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [128]:
newdf.to_csv("newdf.csv")

In [131]:
cols_to_split = ['BusinessParking', 'Ambience', 'BestNights', 'GoodForMeal', 'Music']
for col_to_split in cols_to_split:
    new_df1 = pd.DataFrame(newdf[col_to_split].to_dict()).T
    new_df1.columns = [col_to_split + '_' + str(col) for col in new_df1.columns]
    business_df = business_df.join(new_df1)

In [133]:
business_df.to_csv("attributes.csv")

In [138]:
# columns with non-boolean categorical values:
cols_to_split = ['AgesAllowed', 'Alcohol', 'BYOBCorkage', 'NoiseLevel', 'RestaurantsAttire', 'Smoking', 'WiFi']
new_cat = pd.concat([pd.get_dummies(business_df[col], prefix=col, prefix_sep='_') for col in cols_to_split], axis=1)
# keep all columns (not n-1) because 0's for all of them indicates that the data was missing (useful info)
business_df = pd.concat([business_df, new_cat], axis=1)
business_df.drop(cols_to_split, inplace=True, axis=1)
business_df.head()

KeyError: 'RestaurantsAttire'

In [139]:
business_df

,business_id,name,address,city,state,postal_code,latitude,longitude,stars,review_count,...,GoodForMeal_dinner,GoodForMeal_brunch,GoodForMeal_breakfast,Music_dj,Music_background_music,Music_no_music,Music_jukebox,Music_live,Music_video,Music_karaoke
31,-3AooxIkg38UyUdlz5oXdw,Chase Restaurant,1012 State St,Santa Barbara,CA,93101,34.421931,-119.702185,3.0,436,...,True,False,False,False,False,False,False,False,False,None
404,-BdYhP-12elmFV7oB1iv4A,Corner Tap Room,1905 Cliff Dr,Santa Barbara,CA,93109,34.401382,-119.722472,5.0,41,...,None,None,None,None,None,None,None,None,None,None
433,-nwNPb3G-0L95igrhkvMtw,Panda Express,605 Paseo Nuevo,Santa Barbara,CA,93101,34.418722,-119.700166,2.5,46,...,False,False,False,None,None,None,None,None,None,None
136,-r6nmLB5Vi2TLQCxh0_dtw,South Coast Deli- Carrillo,10 E Carrillo St,Santa Barbara,CA,93101,34.421702,-119.701330,4.0,215,...,False,False,False,None,None,None,None,None,None,None
384,04Ss49U_QKYLotcJMAH8cA,Ikeâ€™s Love & Sandwiches,1936 State St,Santa Barbara,CA,93101,34.430741,-119.714266,4.0,97,...,None,None,None,None,None,None,None,None,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,z9-8KvMAlVK46De-G3sNJQ,Blenders In The Grass,720 State St,Santa Barbara,CA,93101,34.419311,-119.698519,4.0,239,...,None,None,None,None,None,None,None,None,None,None
107,zJpZ-uQ_F0XVgK1u98uWSg,Gloria's Gourmet Kitchen,631 W Carrillo St,Santa Barbara,CA,93101,34.414603,-119.710093,4.5,13,...,None,None,None,None,None,None,None,None,None,None
323,zZrDoiQIUmiVkifJx0h_KA,Old Town Coffee Downtown,"1131 State St, Inside Mosaic Locale",Santa Barbara,CA,93101,34.423056,-119.704515,4.5,8,...,None,None,None,None,None,None,None,None,None,None
337,zeAfmYy9b1gfUJLRBHm6vQ,Presto Pasta,2830 De La Vina St,Santa Barbara,CA,93105,34.437063,-119.725682,4.0,240,...,True,False,False,None,None,None,None,None,None,None
344,ziXR7sUrbKRCNeDqfjibUg,Rudy's Restaurant No 1,305 W Montecito St,Santa Barbara,CA,93101,34.411314,-119.696292,4.0,262,...,True,False,False,None,None,None,None,None,None,None

In [140]:
newdf

,NoiseLevel,BusinessParking,RestaurantsReservations,Alcohol,RestaurantsPriceRange2,BusinessAcceptsCreditCards,OutdoorSeating,BikeParking,WiFi,RestaurantsTakeOut,...,Smoking,BusinessAcceptsBitcoin,DriveThru,ByAppointmentOnly,BYOBCorkage,Corkage,AgesAllowed,Open24Hours,DietaryRestrictions,RestaurantsCounterService
31,u'average',"{'garage': False, 'street': True, 'validated':...",True,'full_bar',2,True,True,True,u'free',True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
404,NaN,"{'garage': False, 'street': False, 'validated'...",False,u'beer_and_wine',NaN,True,True,True,NaN,True,...,u'no',False,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
433,u'average',"{'garage': False, 'street': False, 'validated'...",False,u'none',1,True,True,True,'no',True,...,NaN,NaN,True,NaN,NaN,NaN,NaN,NaN,NaN,NaN
136,u'average',"{'garage': None, 'street': True, 'validated': ...",False,u'none',1,True,True,True,'free',True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
384,NaN,"{'garage': False, 'street': False, 'validated'...",False,u'none',2,True,None,NaN,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
119,u'loud',"{'garage': False, 'street': True, 'validated':...",False,'none',1,True,None,True,u'no',True,...,NaN,NaN,NaN,NaN,'yes_free',False,NaN,NaN,NaN,NaN
107,NaN,None,NaN,u'none',NaN,True,True,True,NaN,True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
323,u'average',"{'valet': False, 'garage': None, 'street': Non...",NaN,NaN,NaN,NaN,True,NaN,u'free',NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
337,u'average',"{'garage': False, 'street': False, 'validated'...",False,u'beer_and_wine',2,True,None,True,u'no',None,...,NaN,NaN,True,False,NaN,NaN,NaN,NaN,NaN,NaN
344,u'average',"{'garage': False, 'street': False, 'validated'...",False,u'beer_and_wine',1,True,True,True,u'no',True,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN